# Feature Extraction - Wiki Page

This wiki page is used to describe the features extracted for all mpower actvities

* Wiki Info
* Feature Documentation

```{r, include = FALSE}
library(synapser)
library(tidyverse)
synapser::synLogin()
```

```{r, include=FALSE}
SYNAPSEFORMATION_PATH = "../synapseformation/manuscript.yaml"
```


```{r include=FALSE}
get_file_view_ref <- function(syn = NULL){
    template_path <- file.path(SYNAPSEFORMATION_PATH)
    if(is.null(syn)){
        project_id <- synFindEntityId(
            yaml::read_yaml(template_path)[[1]]$name)
        file_view_id <- synapser::synFindEntityId(
            "mPower2.0 - File View", project_id)
    }else{
        project_id <- syn$findEntityId(
            yaml::read_yaml(template_path)[[1]]$name)
        file_view_id <- syn$findEntityId(
            "mPower2.0 - File View", project_id)
    }
    return(file_view_id)
}


get_feature_processed_ids <- function(syn = NULL){
    if(is.null(syn)){
        file_view_id <- get_file_view_ref()
        data <- synTableQuery(
            glue::glue("SELECT * FROM {file_view_id}", 
                       file_view_id = file_view_id))$asDataFrame() %>%
            tibble::as_tibble()
    }else{
        file_view_id <- get_file_view_ref(syn)
        data <- syn$tableQuery(
            glue::glue("SELECT * FROM {file_view_id}", 
                       file_view_id = file_view_id))$asDataFrame() %>%
            tibble::as_tibble()
        
    }
    ref_list <- list()
    ref_list$parent_id <- data %>%
        dplyr::filter(
            type == "folder",
            name == "Features - Processed") %>% .$id
    ref_list$tap_20_secs <- data %>%
        dplyr::filter(
            pipelineStep == "feature processing",
            filter == "20 seconds cutoff",
            task == "tapping",
            analysisType == "tapping-v2") %>% .$id
    ref_list$tap <- data %>%
        dplyr::filter(
            is.na(filter),
            pipelineStep == "feature processing",
            task == "tapping",
            analysisType == "tapping-v2") %>% .$id
    return(ref_list)
}
```


```{r, include = FALSE}
SYN_ID_REF <- list(
    feature_processed = get_feature_processed_ids())
FOLDER_ID <- SYN_ID_REF$feature_processed$parent_id
```

### Wiki Info
```{r, message = FALSE, echo=FALSE}
user = synapser::synGetUserProfile()$userName
createdOn = lubridate::now() %>% strftime()

data <- tibble::tibble(
    metadata = c("generated_by", "createdOn"),
    value = c(user, createdOn)
)

knitr::kable(data, "pipe")
```


### Documentation:
```{r, echo=FALSE}
data <- synapser::synGetChildren(
    FOLDER_ID)$asList() %>%
    purrr::map_dfr(function(x){
        id <- x$id
        name <- x$name
        provenance <- synGetProvenance(id)
        description <- provenance$get("description")
        tibble::tibble(
            "id" = id,
            "file_name" = name,
            "description" = description)
    })

knitr::kable(data, "pipe")
```